[package]
name = "hello-rust"
version = "0.1.0"
authors = ["wenqiang <iscona@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
rand = "0.3.14"
serde_json = "1.0"